### ISSUE TITLE
----

### ISSUE THREAD

**Issue by ghost** [compromise-evident/Authorship#1]
I compile like this but I'm not making a mistake, right?

```bash
g++  Authorship.cpp  -o Author
```

```bash
./Author
```

Later when I run the binary it asks me for random numbers but when I enter them I am still waiting

**Comment by compromise-evident** [comment]
You will be waiting for about 20 minutes until it's done creating your fluid Authorship number and one-time keys.

Your commands are ok. You can always run it by entering its path: /home/nikolay/Author
For a simpler solution, log out and log in as root, then place Author in the file system directory called /
Now you can run Author by typing /Author into any terminal as a normal user. Remember, running
things as an executable in the terminal like this--will produce and read from files within your home
directory such as /home/nikolay

Don't forget to grab the important files out of the directory where they were created and place them in
your own folder somewhere on your ENCRYPTED SPINNING DISK DRIVE. If the program needs to read from
and write to those files, keep them there at your discretion--your Authorship.private file should always have
a backup copy, follow the instructions of Authorship as it runs. Demonstrations on youtube is what I really
need here. 

As for my other tools, if you're effective, send and receive using custom RICIN as described on my website.
This way, any machine doing the work of encryption and decryption will is physically separated from the internet.

Thank you for the issue, I will now look into aggressive feedback from the programs as they build your keys.
Users should always be informed about long pauses, and when to wait.
